/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domain.Mesto;
import domain.Musterija;
import domain.Porudzbina;
import domain.Proizvod;
import domain.Radnik;
import domain.StavkaPorudzbina;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import kontroler.Kontroler;
import modeliTabela.TabelProizvodiModel;

/**
 *
 * @author Slobodan
 */
public class FrmListaPorudzbina extends javax.swing.JFrame {

    /**
     * Creates new form FrmListaPorudzbina
     */
    List<Porudzbina> svePorudzbine = new ArrayList<>();
    List<Musterija> sveMusterije = new ArrayList<>();
    Radnik r;

    public FrmListaPorudzbina() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
    }

    public FrmListaPorudzbina(Radnik radnik) {
        initComponents();

        setVisible(true);

        setLocationRelativeTo(null);

        try {
            sveMusterije = Kontroler.getInstance().vratiListuSviMusterija();
        } catch (Exception ex) {
            System.out.println("Greska pri ucitavanju musterija" + ex.getMessage());
        }

        r = radnik;
        popuniTabeluPorudzbina();
        osveziTabeluStavke();
        popuniCbox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPorudzbine = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNapomena = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        lblCena = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        lblIsporuka = new javax.swing.JLabel();
        lblMesto = new javax.swing.JLabel();
        btnObrisiPorudzbinu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnPretraga = new javax.swing.JButton();
        btnOsveziTabelu = new javax.swing.JButton();
        btnIzmeniPorudzbinu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnPrtgMusterija = new javax.swing.JButton();
        cBoxMusterija = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cBoxRadnik = new javax.swing.JComboBox<>();
        btnPrtgRadnik = new javax.swing.JButton();
        btnPrtgProizvod = new javax.swing.JButton();
        cBoxProizvod = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cBoxNacinIsporuke = new javax.swing.JComboBox<>();
        btnPretragaIsporuka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Spisak porudzbina");

        tblPorudzbine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPorudzbine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPorudzbineMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPorudzbine);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Porudzbine");

        txtNapomena.setColumns(20);
        txtNapomena.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNapomena.setRows(5);
        txtNapomena.setEnabled(false);
        jScrollPane2.setViewportView(txtNapomena);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Napomena");

        lblCena.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        lblCena.setForeground(new java.awt.Color(255, 0, 0));
        lblCena.setText("Ukupna Cena:");

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStavke.setEnabled(false);
        jScrollPane3.setViewportView(tblStavke);

        lblIsporuka.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIsporuka.setText("Nacin isporuke: ");

        lblMesto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMesto.setText("Lokacija:");

        btnObrisiPorudzbinu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnObrisiPorudzbinu.setText("Obrisi porudzbinu");
        btnObrisiPorudzbinu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPorudzbinuActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ID porudzbine");

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnPretraga.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnPretraga.setText("Pretrazi");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        btnOsveziTabelu.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnOsveziTabelu.setText("Osvezi tabelu");
        btnOsveziTabelu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsveziTabeluActionPerformed(evt);
            }
        });

        btnIzmeniPorudzbinu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIzmeniPorudzbinu.setText("Izmeni porudzbinu");
        btnIzmeniPorudzbinu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniPorudzbinuActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Musterija");

        btnPrtgMusterija.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnPrtgMusterija.setText("Pretrazi");
        btnPrtgMusterija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrtgMusterijaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Radnik");

        btnPrtgRadnik.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnPrtgRadnik.setText("Pretrazi");
        btnPrtgRadnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrtgRadnikActionPerformed(evt);
            }
        });

        btnPrtgProizvod.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnPrtgProizvod.setText("Pretrazi");
        btnPrtgProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrtgProizvodActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Proizvod");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Nacin isporuke");

        cBoxNacinIsporuke.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dostava", "Preuzimanje" }));
        cBoxNacinIsporuke.setSelectedIndex(-1);

        btnPretragaIsporuka.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnPretragaIsporuka.setText("Pretrazi");
        btnPretragaIsporuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaIsporukaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretraga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cBoxMusterija, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrtgMusterija)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cBoxRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrtgRadnik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cBoxProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrtgProizvod)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnObrisiPorudzbinu, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnIzmeniPorudzbinu)
                                    .addComponent(cBoxNacinIsporuke, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(btnPretragaIsporuka, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2)
                            .addComponent(lblIsporuka, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btnOsveziTabelu)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraga)
                    .addComponent(jLabel4)
                    .addComponent(btnPrtgMusterija)
                    .addComponent(cBoxMusterija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnPrtgRadnik)
                    .addComponent(cBoxRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnPrtgProizvod)
                    .addComponent(cBoxProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIsporuka)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cBoxNacinIsporuke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPretragaIsporuka)
                                .addGap(36, 36, 36)
                                .addComponent(btnObrisiPorudzbinu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnIzmeniPorudzbinu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblMesto)
                        .addGap(13, 13, 13)
                        .addComponent(lblCena)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOsveziTabelu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPorudzbineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPorudzbineMouseClicked

        int red = tblPorudzbine.getSelectedRow();

        if (red == -1) {
            return;
        }

        int idPorudzbine = (int) tblPorudzbine.getValueAt(red, 0);
        int idMusterija = 0;
        String napomena = "";
        int cena = 0;
        String isporuka = "";

        for (Porudzbina p : svePorudzbine) {
            if (idPorudzbine == p.getIdPorudzbina()) {
                napomena = p.getNapomena();
                cena = p.getUkupnaCena();
                isporuka = p.getNacinIsporuke();
                idMusterija = p.getIdMusterija();
            }
        }

        lblCena.setText("Ukupna cena: " + cena);
        txtNapomena.setText(napomena);
        lblIsporuka.setText("Nacin isporuke: " + isporuka);

        if (isporuka.equals("Dostava")) {
            Musterija m = vratiMusteriju(idMusterija);
            Mesto mesto = vratiMesto(m.getIdMesto());
            lblMesto.setText("Lokacija: " + mesto);
        } else {
            lblMesto.setText("Lokacija: /");
        }

        popuniStavke(idPorudzbine);

    }//GEN-LAST:event_tblPorudzbineMouseClicked

    private void btnObrisiPorudzbinuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPorudzbinuActionPerformed

        int red = tblPorudzbine.getSelectedRow();

        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Nije izabrana porudzbina!");
            return;
        }

        int idPor = (int) tblPorudzbine.getValueAt(red, 0);
        Porudzbina p=new Porudzbina(idPor, null, 0, LocalDateTime.MIN, null, 0, 0);

        int odgovor = JOptionPane.showConfirmDialog(
                null,
                "Brisanjem porudžbine biće obrisane i sve njene stavke.\nDa li ste sigurni da želite da nastavite?",
                "Potvrda brisanja",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (odgovor == JOptionPane.YES_OPTION) {

            try {
                Kontroler.getInstance().obrisiPorudzbina(p);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise porudzbinu");
                System.out.println("Greska pri brisanju porudzbine!" + ex.getMessage());
                return;
            }

            JOptionPane.showMessageDialog(this, "Sistem je obrisao porudzbinu!");
            popuniTabeluPorudzbina();
            osveziTabeluStavke();

            lblIsporuka.setText("Nacin isporuke:");
            txtNapomena.setText("");
            lblMesto.setText("Lokacija:");
            lblCena.setText("Ukupna cena:");

        } else {
            JOptionPane.showMessageDialog(this, "Brisanje otkazano");
        }


    }//GEN-LAST:event_btnObrisiPorudzbinuActionPerformed

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed

        if (txtId.getText() == "" || !txtId.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Unesi id broj!");
            return;
        }

        int idPor = Integer.parseInt(txtId.getText());

        popuniTabeluPorudzbina(idPor);

        txtId.setText("");
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void btnOsveziTabeluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsveziTabeluActionPerformed
        popuniTabeluPorudzbina();
        osveziTabeluStavke();
        lblIsporuka.setText("Nacin isporuke:");
        txtNapomena.setText("");
        lblMesto.setText("Lokacija:");
        lblCena.setText("Ukupna cena:");
    }//GEN-LAST:event_btnOsveziTabeluActionPerformed

    private void btnIzmeniPorudzbinuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniPorudzbinuActionPerformed

        int red = tblPorudzbine.getSelectedRow();

        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Nije izabrana porudzbina!");
            return;
        }

        int idPor = (int) tblPorudzbine.getValueAt(red, 0);
        
        JOptionPane.showMessageDialog(this, "Sistem je nasao porudzbinu");

        FrmKreirajPorudzbinu fkp = new FrmKreirajPorudzbinu(idPor, r);

        btnOsveziTabeluActionPerformed(evt);

    }//GEN-LAST:event_btnIzmeniPorudzbinuActionPerformed

    private void btnPrtgMusterijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrtgMusterijaActionPerformed

        try {

            Musterija m = (Musterija) cBoxMusterija.getSelectedItem();
            
            Porudzbina p=new Porudzbina(0, null, 0, null, null, 0, m.getIdMusterija());

            List<Porudzbina> porudzbine = Kontroler.getInstance().vratiListuPorudzbinaPoKriterijumu(p);

            if (porudzbine.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nema porudzbina za izabranu musteriju");
                return;
            }

            popuniTabeluPorudzbina(porudzbine);
            cBoxMusterija.setSelectedIndex(-1);

        } catch (Exception ex) {
            System.out.println("Greska kod vracanje liste porudzbina kriterijum Musterija" + ex.getMessage());
        }

    }//GEN-LAST:event_btnPrtgMusterijaActionPerformed

    private void btnPrtgRadnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrtgRadnikActionPerformed

        try {

            Radnik r = (Radnik) cBoxRadnik.getSelectedItem();
            
            Porudzbina p=new Porudzbina(0, null, 0, null, null, r.getIdRadnik(), 0);

            List<Porudzbina> porudzbine = Kontroler.getInstance().vratiListuPorudzbinaPoKriterijumu(p);

            if (porudzbine.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nema porudzbina za izabranog radnika");
                return;
            }

            popuniTabeluPorudzbina(porudzbine);
            cBoxRadnik.setSelectedIndex(-1);

        } catch (Exception ex) {
            cBoxRadnik.setSelectedIndex(-1);
            System.out.println("Greska kod vracanje liste porudzbina kriterijum Radnik" + ex.getMessage());
        }

    }//GEN-LAST:event_btnPrtgRadnikActionPerformed

    private void btnPrtgProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrtgProizvodActionPerformed

        try {

            Proizvod p = (Proizvod) cBoxProizvod.getSelectedItem();
            
            Porudzbina por=new Porudzbina(0, null, 0, null, null, 0, 0);
            por.setPom(p);

            List<Porudzbina> porudzbine = Kontroler.getInstance().vratiListuPorudzbinaPoKriterijumu(por);

            if (porudzbine.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nema porudzbina za izabran proizvod");
                return;
            }

            popuniTabeluPorudzbina(porudzbine);
            cBoxProizvod.setSelectedIndex(-1);

        } catch (Exception ex) {
            cBoxProizvod.setSelectedIndex(-1);
            System.out.println("Greska kod vracanje liste porudzbina kriterijum Proizvod" + ex.getMessage());
        }


    }//GEN-LAST:event_btnPrtgProizvodActionPerformed

    private void btnPretragaIsporukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaIsporukaActionPerformed
        try {

            String nacinIsporuke = (String) cBoxNacinIsporuke.getSelectedItem();

            Porudzbina p=new Porudzbina(0, nacinIsporuke, 0, null, null, 0, 0);

            List<Porudzbina> porudzbine = Kontroler.getInstance().vratiListuPorudzbinaPoKriterijumu(p);

            if (porudzbine.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nema porudzbina za izabran nacin isporuke");
                return;
            }

            popuniTabeluPorudzbina(porudzbine);
            cBoxNacinIsporuke.setSelectedIndex(-1);

        } catch (Exception ex) {
            cBoxNacinIsporuke.setSelectedIndex(-1);
            System.out.println("Greska kod vracanje liste porudzbina kriterijum nacin isporuke" + ex.getMessage());
        }
    }//GEN-LAST:event_btnPretragaIsporukaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListaPorudzbina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListaPorudzbina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListaPorudzbina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListaPorudzbina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListaPorudzbina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniPorudzbinu;
    private javax.swing.JButton btnObrisiPorudzbinu;
    private javax.swing.JButton btnOsveziTabelu;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JButton btnPretragaIsporuka;
    private javax.swing.JButton btnPrtgMusterija;
    private javax.swing.JButton btnPrtgProizvod;
    private javax.swing.JButton btnPrtgRadnik;
    private javax.swing.JComboBox<Musterija> cBoxMusterija;
    private javax.swing.JComboBox<String> cBoxNacinIsporuke;
    private javax.swing.JComboBox<Proizvod> cBoxProizvod;
    private javax.swing.JComboBox<Radnik> cBoxRadnik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCena;
    private javax.swing.JLabel lblIsporuka;
    private javax.swing.JLabel lblMesto;
    private javax.swing.JTable tblPorudzbine;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextArea txtNapomena;
    // End of variables declaration//GEN-END:variables

    private void popuniTabeluPorudzbina() {
        String[] kolone = {"Id", "Kupac", "Datum", "Vreme"};
        TabelProizvodiModel dt = new TabelProizvodiModel(kolone);

        // Postavljanje modela na tabelu
        tblPorudzbine.setModel(dt);

        try {
            svePorudzbine = Kontroler.getInstance().vratiListuSviPorudzbina();
        } catch (Exception ex) {
            System.out.println("Greska pri ucitavanju porudzbina " + ex.getMessage());
            svePorudzbine = null;
            return;
        }
        int brojac = 0;

        for (Porudzbina p : svePorudzbine) {
            dt.setRowCount(brojac + 1);

            dt.setValueAt(p.getIdPorudzbina(), brojac, 0);
            dt.setValueAt(vratiMusteriju(p.getIdMusterija()), brojac, 1);
            dt.setValueAt(p.getDatumVreme().toLocalDate(), brojac, 2);
            dt.setValueAt(p.getDatumVreme().toLocalTime(), brojac, 3);

            brojac++;
        }

        tblPorudzbine.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblPorudzbine.setRowSelectionAllowed(true);
        tblPorudzbine.setColumnSelectionAllowed(false);

    }

    private Musterija vratiMusteriju(int idMusterija) {

        for (Musterija m : sveMusterije) {
            if (m.getIdMusterija() == idMusterija) {
                return m;
            }
        }

        return null;
    }

    private void popuniStavke(int idPorudzbine) {

        try {

            String[] kolone = {"Rb", "Proizvod", "Kolicina", "Cena"};
            TabelProizvodiModel dt = new TabelProizvodiModel(kolone);

            // Postavljanje modela na tabelu
            tblStavke.setModel(dt);

            List<StavkaPorudzbina> stavke;

            try {
                stavke = Kontroler.getInstance().vratiListuSviStavkePorudzbine(idPorudzbine);
            } catch (Exception ex) {
                System.out.println("Greska pri ucitavanju stavki " + ex.getMessage());
                stavke = null;
                return;
            }
            int brojac = 0;

            for (StavkaPorudzbina sp : stavke) {
                dt.setRowCount(brojac + 1);

                dt.setValueAt(sp.getRb(), brojac, 0);
                dt.setValueAt(vratiProizvod(sp.getIdProizvod()), brojac, 1);
                dt.setValueAt(sp.getKolicina(), brojac, 2);
                dt.setValueAt(sp.getCena(), brojac, 3);

                brojac++;
            }

        } catch (Exception ex) {
            System.out.println("Greska pri ucitavanju liste stavki" + ex.getMessage());
        }

    }

    private Proizvod vratiProizvod(int idProizvod) {

        try {
            List<Proizvod> proizvodi = Kontroler.getInstance().vratiListuSviProizvodi();

            for (Proizvod p : proizvodi) {
                if (idProizvod == p.getIdProizvod()) {
                    return p;
                }
            }

        } catch (Exception ex) {
            System.out.println("Greska pri ucitavnju proizvoda" + ex.getMessage());
        }

        return null;

    }

    private Mesto vratiMesto(int idMesto) {

        try {
            Mesto m=new Mesto(idMesto, null, null);
            return Kontroler.getInstance().pretraziMesta(m);
        } catch (Exception ex) {
            System.out.println("Greska pri ucitavnju mesta" + ex.getMessage());
        }

        return null;
    }

    private void osveziTabeluStavke() {
        String[] kolone = {"Rb", "Proizvod", "Kolicina", "Cena"};
        TabelProizvodiModel dt = new TabelProizvodiModel(kolone);

        tblStavke.setModel(dt);

        int brojac = 0;

        dt.setRowCount(0);

    }

    private void popuniTabeluPorudzbina(int idPor) {
        try {
            Porudzbina p=new Porudzbina(idPor, null, -1, null, null, -1, -1);
            p = Kontroler.getInstance().pretraziPorudzbina(p);

            if (p.getNacinIsporuke() == null) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje porudzbine po zadatim kriterijumima");
                return;
            }

            JOptionPane.showMessageDialog(this, "Sistem je nasao porudzbine sa zadatim kriterijumima");
            
            String[] kolone = {"Id", "Kupac", "Datum", "Vreme"};
            TabelProizvodiModel dt = new TabelProizvodiModel(kolone);

            tblPorudzbine.setModel(dt);

            dt.setRowCount(1);

            dt.setValueAt(p.getIdPorudzbina(), 0, 0);
            dt.setValueAt(vratiMusteriju(p.getIdMusterija()), 0, 1);
            dt.setValueAt(p.getDatumVreme().toLocalDate(), 0, 2);
            dt.setValueAt(p.getDatumVreme().toLocalTime(), 0, 3);

            tblPorudzbine.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            tblPorudzbine.setRowSelectionAllowed(true);
            tblPorudzbine.setColumnSelectionAllowed(false);

        } catch (Exception ex) {
            System.out.println("Neuspela pretraga mesta po idiju" + ex.getMessage());
        }
    }

    private void popuniCbox() {

        try {
            List<Musterija> musterije = Kontroler.getInstance().vratiListuSviMusterija();

            List<Radnik> radnici = Kontroler.getInstance().vratiListuSviRadnik();

            List<Proizvod> proizvodi = Kontroler.getInstance().vratiListuSviProizvodi();

            cBoxMusterija.removeAllItems();
            cBoxRadnik.removeAllItems();
            cBoxProizvod.removeAllItems();

            for (Musterija m : musterije) {
                cBoxMusterija.addItem(m);
            }

            for (Radnik radnik : radnici) {
                cBoxRadnik.addItem(radnik);
            }

            for (Proizvod p : proizvodi) {
                cBoxProizvod.addItem(p);
            }

            cBoxMusterija.setSelectedIndex(-1);
            cBoxRadnik.setSelectedIndex(-1);
            cBoxProizvod.setSelectedIndex(-1);

        } catch (Exception ex) {
            System.out.println("Greška pri učitavanju comboBoxova" + ex.getMessage());
        }
    }

    private void popuniTabeluPorudzbina(List<Porudzbina> porudzbine) {
        String[] kolone = {"Id", "Kupac", "Datum", "Vreme"};
        TabelProizvodiModel dt = new TabelProizvodiModel(kolone);

        // Postavljanje modela na tabelu
        tblPorudzbine.setModel(dt);

        int brojac = 0;

        for (Porudzbina p : porudzbine) {
            dt.setRowCount(brojac + 1);

            dt.setValueAt(p.getIdPorudzbina(), brojac, 0);
            dt.setValueAt(vratiMusteriju(p.getIdMusterija()), brojac, 1);
            dt.setValueAt(p.getDatumVreme().toLocalDate(), brojac, 2);
            dt.setValueAt(p.getDatumVreme().toLocalTime(), brojac, 3);

            brojac++;
        }

        tblPorudzbine.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblPorudzbine.setRowSelectionAllowed(true);
        tblPorudzbine.setColumnSelectionAllowed(false);
    }

}
