/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package forme;

import domain.Mesto;
import domain.Musterija;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import kontroler.Kontroler;

/**
 *
 * @author Slobodan
 */
public class KreirajMusterija extends java.awt.Dialog {

    /**
     * Creates new form KreirajMusterija
     */
    public KreirajMusterija(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        setTitle("Kreiraj musteriju");

        initComponents();

        this.setLocationRelativeTo(null);

        setVisible(true);

        popuniCBoxMesta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtBrTelefona = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        cboxMesto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        brnKreirajMesto = new javax.swing.JButton();
        lblGreska = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setText("Ime");

        jLabel2.setText("Prezime");

        jLabel3.setText("Broj telefona");

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel4.setText("Mesto");

        brnKreirajMesto.setText("Kreiraj mesto");
        brnKreirajMesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnKreirajMestoActionPerformed(evt);
            }
        });

        lblGreska.setForeground(new java.awt.Color(255, 0, 0));
        lblGreska.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btnSacuvaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIme)
                    .addComponent(txtPrezime)
                    .addComponent(txtBrTelefona)
                    .addComponent(cboxMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(brnKreirajMesto)
                .addGap(60, 60, 60))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGreska, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBrTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboxMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(brnKreirajMesto)))
                .addGap(18, 18, 18)
                .addComponent(lblGreska, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSacuvaj)
                .addGap(39, 39, 39))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void brnKreirajMestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnKreirajMestoActionPerformed

        KreirajMesto kmm = new KreirajMesto(null, true);

        popuniCBoxMesta();

    }//GEN-LAST:event_brnKreirajMestoActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        Mesto mesto = (Mesto) cboxMesto.getSelectedItem();
        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        String brTelefona = txtBrTelefona.getText().trim();

        if (ime.isEmpty()) {
            lblGreska.setText("Ime je obavezno.");
            return;
        }

        if (prezime.isEmpty()) {
            lblGreska.setText("Prezime je obavezno.");
            return;
        }

        if (brTelefona.isEmpty()) {
            lblGreska.setText("Broj telefona je obavezan.");
            return;
        }

        // Provera formata broja telefona (broj telefona može imati 9 ili 10 cifara)
        if (!brTelefona.matches("\\d{9,10}")) {
            lblGreska.setText("Broj telefona mora sadržati 9 ili 10 cifara.");
            return;
        }
        
        if (mesto == null) {
            lblGreska.setText("Molimo izaberite mesto.");
            return;
        }

        Musterija m = new Musterija(-1, txtIme.getText(), txtPrezime.getText(), txtBrTelefona.getText(), mesto.getIdMesto());

        try {
            if (Kontroler.getInstance().kreirajMusterija(m)) {
                JOptionPane.showMessageDialog(null, "Uspesno kreirana musterija");
                this.dispose();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Greska pri kreiranju musterije");
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KreirajMusterija dialog = new KreirajMusterija(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnKreirajMesto;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<Mesto> cboxMesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGreska;
    private javax.swing.JTextField txtBrTelefona;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void popuniCBoxMesta() {
        new Thread(() -> {
            try {
                List<Mesto> mesta = Kontroler.getInstance().vratiListuSviMesta();
                
                cboxMesto.removeAllItems();
                
                for (Mesto mesto : mesta) {
                    cboxMesto.addItem(mesto);
                }

                cboxMesto.setSelectedIndex(-1);

            } catch (Exception ex) {
                System.out.println("Greška pri učitavanju mesta: " + ex.getMessage());
            }
        }).start();
    }

}
