/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domain.Mesto;
import domain.RadnaSmena;
import java.awt.Color;
import java.time.LocalTime;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import kontroler.Kontroler;
import modeliTabela.TabelProizvodiModel;

/**
 *
 * @author Slobodan
 */
public class ObrisiRadnaSmena extends javax.swing.JFrame {

    /**
     * Creates new form FrmSveRadneSmene
     */
    public ObrisiRadnaSmena() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRadneSmene = new javax.swing.JTable();
        btnObrisi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnPretraga = new javax.swing.JButton();
        lblPretraga = new javax.swing.JLabel();
        txtIdRadnoMesto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Obrisi radnu smenu");

        tblRadneSmene.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRadneSmene);

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jButton1.setText("Osvezi tabelu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnPretraga.setText("Pretraga");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        lblPretraga.setBackground(new java.awt.Color(255, 0, 0));
        lblPretraga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Unesi id radne smene");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdRadnoMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addComponent(btnPretraga)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdRadnoMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(91, 91, 91)
                        .addComponent(btnObrisi))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        int selectedRow = tblRadneSmene.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Nema selektovane radne smene", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int idRadneSmene = (int) tblRadneSmene.getValueAt(selectedRow, 0);
        RadnaSmena rs = new RadnaSmena(idRadneSmene, null, null, null);

        try {
            if (Kontroler.getInstance().obrisiRadnaSmena(rs)) {
                JOptionPane.showMessageDialog(null, "Sistem je obrisao radnu smenu");
                popuniTabelu();
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Sistem ne moze da obrise radnu smenu");
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        popuniTabelu();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed

        if (txtIdRadnoMesto.getText() == "" || !txtIdRadnoMesto.getText().matches("^\\d+$")) {
            lblPretraga.setText("Unesi neki broj");
            lblPretraga.setForeground(Color.RED);
            return;
        }

        lblPretraga.setText("");

        int idRadnaSmena = Integer.parseInt(txtIdRadnoMesto.getText());

        System.out.println(idRadnaSmena);
        popuniTabelu(idRadnaSmena);
    }//GEN-LAST:event_btnPretragaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObrisiRadnaSmena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObrisiRadnaSmena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObrisiRadnaSmena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObrisiRadnaSmena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObrisiRadnaSmena().setVisible(true);
            }
        });
    }

    private void popuniTabelu() {

        // DefaultTableModel koji onemogućava uređivanje ćelija
        DefaultTableModel dt = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // Postavljanje modela na tabelu
        tblRadneSmene.setModel(dt);

        dt.setColumnCount(4);
        dt.setRowCount(0);

        String[] kolone = {"Id", "Naziv", "Vreme od", "Vreme do"};
        dt.setColumnIdentifiers(kolone);

        List<RadnaSmena> sveRadneSmene;
        try {
            sveRadneSmene = Kontroler.getInstance().vratiListuSviRadnaSmena();
        } catch (Exception ex) {
            System.out.println("Greska pri ucitavanju radnih smena " + ex.getMessage());
            sveRadneSmene = null;
            return;
        }
        int brojac = 0;

        if (sveRadneSmene == null || sveRadneSmene.isEmpty()) {
            System.out.println("Lista radnih smena je prazna");
            return;
        }

        for (RadnaSmena radnaSmena : sveRadneSmene) {
            dt.setRowCount(brojac + 1);

            dt.setValueAt(radnaSmena.getIdRadnaSmena(), brojac, 0);
            dt.setValueAt(radnaSmena.getNaziv(), brojac, 1);
            dt.setValueAt(radnaSmena.getVremeOd(), brojac, 2);
            dt.setValueAt(radnaSmena.getVremeDo(), brojac, 3);

            brojac++;
        }

        tblRadneSmene.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblRadneSmene.setRowSelectionAllowed(true);
        tblRadneSmene.setColumnSelectionAllowed(false);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPretraga;
    private javax.swing.JTable tblRadneSmene;
    private javax.swing.JTextField txtIdRadnoMesto;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu(int idRadnaSmena) {
        try {
            RadnaSmena rs=new RadnaSmena(idRadnaSmena, "", null, null);
            rs = Kontroler.getInstance().pretraziRadnaSmena(rs);

            if (rs.getNaziv() == null) {
                JOptionPane.showMessageDialog(this, "Ne postoji radna smena sa unetim id-ijem, probaj opet");
                return;
            }

            String[] kolone = {"Id", "Naziv", "Vreme od", "Vreme do"};
            TabelProizvodiModel dt = new TabelProizvodiModel(kolone);

            tblRadneSmene.setModel(dt);

            dt.setRowCount(1);

            dt.setValueAt(rs.getIdRadnaSmena(), 0, 0);
            dt.setValueAt(rs.getNaziv(), 0, 1);
            dt.setValueAt(rs.getVremeOd(), 0, 2);
            dt.setValueAt(rs.getVremeDo(), 0, 3);

            tblRadneSmene.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            tblRadneSmene.setRowSelectionAllowed(true);
            tblRadneSmene.setColumnSelectionAllowed(false);

        } catch (Exception ex) {
            System.out.println("Neuspela pretraga radnih smena po idiju" + ex.getMessage());
        }
    }
}
