/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domain.Radnik;
import domain.RadnaSmena;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import kontroler.Kontroler;
import modeliTabela.TabelProizvodiModel;

/**
 *
 * @author Slobodan
 */
public class UrediRadnik extends javax.swing.JFrame {

    /**
     * Creates new form PromeniRadnik
     */
    public UrediRadnik() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        popuniTabelu();
        popuniCbox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtIme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        btnIzmeniRadnika = new javax.swing.JButton();
        txtKorIme = new javax.swing.JTextField();
        btnIzaberiRadnika = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSviRadnici = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtStaraLoznika = new javax.swing.JPasswordField();
        txtNovaLozinka = new javax.swing.JPasswordField();
        btnPretraga = new javax.swing.JButton();
        lblGreska = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboxRS = new javax.swing.JComboBox<>();
        btnPretraga1 = new javax.swing.JButton();
        lblGreska1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Uredi radnika");

        lblID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton1.setText("Osvezi tabelu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Korisnicko ime:");

        btnIzmeniRadnika.setText("Izmeni");
        btnIzmeniRadnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniRadnikaActionPerformed(evt);
            }
        });

        btnIzaberiRadnika.setText("Izaberi radnika");
        btnIzaberiRadnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiRadnikaActionPerformed(evt);
            }
        });

        jLabel1.setText("Id:");

        tblSviRadnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSviRadnici);

        jLabel2.setText("Ime:");

        jLabel3.setText("Prezime:");

        jLabel5.setText("Stara lozinka:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nova lozinka:");

        txtNovaLozinka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNovaLozinkaActionPerformed(evt);
            }
        });

        btnPretraga.setText("Pretraga");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        lblGreska.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGreska.setForeground(new java.awt.Color(255, 0, 0));
        lblGreska.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel7.setText("Unesi ime:");

        jLabel9.setText("Filter radna smena:");

        cboxRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxRSActionPerformed(evt);
            }
        });

        btnPretraga1.setText("Pretraga");
        btnPretraga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraga1ActionPerformed(evt);
            }
        });

        lblGreska1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGreska1.setForeground(new java.awt.Color(255, 0, 0));
        lblGreska1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(cboxRS, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPretraga1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPretraga)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGreska, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGreska1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIzaberiRadnika))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKorIme, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStaraLoznika, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIzmeniRadnika)
                                    .addComponent(txtNovaLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGreska1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(cboxRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPretraga1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(btnPretraga))
                    .addComponent(lblGreska, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtKorIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtStaraLoznika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNovaLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(32, 32, 32)
                        .addComponent(btnIzmeniRadnika)
                        .addGap(12, 12, 12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(btnIzaberiRadnika))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        popuniTabelu();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnIzmeniRadnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniRadnikaActionPerformed

        if (lblID.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nije izabran radnik");
            return;
        }

        String staraLoznika = String.valueOf(txtStaraLoznika.getPassword());
        int idRadnika = Integer.valueOf(lblID.getText());

        List<Radnik> sviRadnici = new ArrayList<>();
        try {
            sviRadnici = Kontroler.getInstance().vratiListuSviRadnik();
        } catch (Exception ex) {
            System.out.println("Greska pri ucitavanju liste radnika" + ex.getMessage());
        }

        for (Radnik r : sviRadnici) {
            if (r.getIdRadnik() == idRadnika) {
                if (!staraLoznika.equals(r.getLoznika())) {
                    JOptionPane.showMessageDialog(this, "Nije moguce izmeniti radnika, stara loznika nije ispravna");
                    return;
                }
            }
        }

        Radnik r = new Radnik(Integer.valueOf(lblID.getText()), txtIme.getText(), txtPrezime.getText(),
                txtKorIme.getText(), String.valueOf(txtNovaLozinka.getPassword()));

        try {
            Kontroler.getInstance().promeniRadnika(r);

            JOptionPane.showMessageDialog(this, "Uspesno izmenjen radnik");

            popuniTabelu();

            lblID.setText("");
            txtIme.setText("");
            txtPrezime.setText("");
            txtKorIme.setText("");
            txtStaraLoznika.setText("");
            txtNovaLozinka.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Neuspsna izmena radnika");
            System.out.println(ex.getMessage());

        }


    }//GEN-LAST:event_btnIzmeniRadnikaActionPerformed

    private void btnIzaberiRadnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiRadnikaActionPerformed

        if (tblSviRadnici.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Nije izabran radnik iz tabele");
            return;
        }

        int red = tblSviRadnici.getSelectedRow();
        int idRadnik = (int) tblSviRadnici.getValueAt(red, 0);

        List<Radnik> sviRadnici = new ArrayList<>();

        try {
            sviRadnici = Kontroler.getInstance().vratiListuSviRadnik();
        } catch (Exception ex) {
            System.out.println("Greska pri ucitavanju liste radnika" + ex.getMessage());
        }

        Radnik izabranRadnik = null;

        for (Radnik r : sviRadnici) {
            if (r.getIdRadnik() == idRadnik) {
                izabranRadnik = r;
            }
        }

        lblID.setText(String.valueOf(izabranRadnik.getIdRadnik()));
        txtIme.setText(izabranRadnik.getIme());
        txtPrezime.setText(izabranRadnik.getPrezime());
        txtKorIme.setText(izabranRadnik.getKorIme());

    }//GEN-LAST:event_btnIzaberiRadnikaActionPerformed

    private void txtNovaLozinkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNovaLozinkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNovaLozinkaActionPerformed

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed

        String pretraga = txtPretraga.getText();
        
        Radnik r=new Radnik(0, pretraga, null, null, null);

        List<Radnik> radnici = new ArrayList<>();
        try {
            radnici = Kontroler.getInstance().vratiListuRadnik(r);
            lblGreska.setText("");
            popuniTabelu(radnici);
        } catch (Exception ex) {
            lblGreska.setText("Nema radnika za uneti kriterijum");
            System.out.println("Greska kod vracanja radnika sa zadatim vrednostima" + ex.getMessage());
        }

        txtPretraga.setText("");
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void btnPretraga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraga1ActionPerformed
        RadnaSmena rs = (RadnaSmena) cboxRS.getSelectedItem();

        List<Radnik> radnici = new ArrayList<>();
        try {
            radnici = Kontroler.getInstance().vratiListuRadnik(rs);
            lblGreska1.setText("");
            popuniTabelu(radnici);
        } catch (Exception ex) {
            lblGreska1.setText("Nema radnika za izabranu smenu");
            System.out.println("Greska kod vracanja radnika sa zadatim vrednostima" + ex.getMessage());
            popuniTabelu();
        }

        cboxRS.setSelectedIndex(-1);
    }//GEN-LAST:event_btnPretraga1ActionPerformed

    private void cboxRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxRSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxRSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrediRadnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrediRadnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrediRadnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrediRadnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UrediRadnik().setVisible(true);
            }
        });
    }

    private void popuniTabelu() {
        String[] kolone = {"Id", "Ime", "Prezime", "Korisnicko ime"};
        TabelProizvodiModel dt = new TabelProizvodiModel(kolone);

        // Postavljanje modela na tabelu
        tblSviRadnici.setModel(dt);

        List<Radnik> sviRadnici;

        try {
            sviRadnici = Kontroler.getInstance().vratiListuSviRadnik();
        } catch (Exception ex) {
            System.out.println("Greska pri ucitavanju radnika " + ex.getMessage());
            sviRadnici = null;
            return;
        }
        int brojac = 0;

        for (Radnik r : sviRadnici) {
            dt.setRowCount(brojac + 1);

            dt.setValueAt(r.getIdRadnik(), brojac, 0);
            dt.setValueAt(r.getIme(), brojac, 1);
            dt.setValueAt(r.getPrezime(), brojac, 2);
            dt.setValueAt(r.getKorIme(), brojac, 3);

            brojac++;
        }

        tblSviRadnici.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblSviRadnici.setRowSelectionAllowed(true);
        tblSviRadnici.setColumnSelectionAllowed(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzaberiRadnika;
    private javax.swing.JButton btnIzmeniRadnika;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JButton btnPretraga1;
    private javax.swing.JComboBox<RadnaSmena> cboxRS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGreska;
    private javax.swing.JLabel lblGreska1;
    private javax.swing.JLabel lblID;
    private javax.swing.JTable tblSviRadnici;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtKorIme;
    private javax.swing.JPasswordField txtNovaLozinka;
    private javax.swing.JTextField txtPretraga;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JPasswordField txtStaraLoznika;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu(List<Radnik> radnici) {

        String[] kolone = {"Id", "Ime", "Prezime", "Korisnicko ime"};
        TabelProizvodiModel dt = new TabelProizvodiModel(kolone);

        tblSviRadnici.setModel(dt);

        int brojac = 0;

        for (Radnik r : radnici) {
            dt.setRowCount(brojac + 1);

            dt.setValueAt(r.getIdRadnik(), brojac, 0);
            dt.setValueAt(r.getIme(), brojac, 1);
            dt.setValueAt(r.getPrezime(), brojac, 2);
            dt.setValueAt(r.getKorIme(), brojac, 3);

            brojac++;
        }

        tblSviRadnici.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblSviRadnici.setRowSelectionAllowed(true);
        tblSviRadnici.setColumnSelectionAllowed(false);

    }

    private void popuniCbox() {
        try {
            List<RadnaSmena> smene = Kontroler.getInstance().vratiListuSviRadnaSmena();

            cboxRS.removeAllItems();

            for (RadnaSmena rs : smene) {
                cboxRS.addItem(rs);
            }

            cboxRS.setSelectedIndex(-1);

        } catch (Exception ex) {
            System.out.println("Greška pri učitavanju smena: " + ex.getMessage());
        }

    }

}
