/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package komunikacija;

/**
 *
 * @author Slobodan
 */
public enum Operacija {
    KREIRAJ_RADNIKA, LOGIN, VRATI_PROIZVODE, VRATI_RADNESMENE, KREIRAJ_PROIZVOD, KREIRAJ_RADNUSMENU, OBRISI_RADNUSMENU,
    KREIRAJ_MESTO, VRATI_MESTA, KREIRAJ_MUSTERIJA, OBRISI_PROIZVOD, OBRISI_MESTO, OBRISI_RADNIKA, VRATI_MUSTERIJE,
    OBRISI_MUSTERIJU, PROMENI_PROIZVOD, PROMENI_MESTO, PROMENI_RADNU_SMENU, PROMENI_MUSTERIJU,
    VRATI_RADNIKE, PROMENI_RADNIKA, PRETRAGA_PROIZVODA,PRETRAGA_MESTA, PRETRAGA_MUSTERIJA, PRETRAGA_RADNIH_SMENA,
    PRETRAGA_RADNIKA, VRATI_MESTA_PO_GRADU,VRATI_MUSTERIJU_PO_IMENU, VRATI_PROIZVOD_PO_NAZIVU,
    VRATI_RADNIKE_PO_IMENU, VRATI_RADNE_SMENE_PO_NAZIVU, VRATI_RADNIK_RADNA_SMENA, KREIRAJ_RADNIK_RADNA_SMENA,
    OBRISI_RADNIK_RADNA_SMENA, PROMENI_RADNIK_RADNA_SMENA, KREIRAJ_PORUDZBINU, KREIRAJ_STAVKU_PORUDZBINE,
    VRATI_LISTU_STAVKE_PORUDZBINE, PROMENI_PORUDZBINA, OBRISI_STAVKA_PORUDZBINE,
    VRATI_LISTU_SVE_PORUDZBINE, OBRISI_PORUDZBINA,
    
    
}
